const SET_GAME = 'SET_GAME';
const SET_SCORE = 'SET_SCORE';

const SET_PLATFORMS = 'SET_PLATFORMS';
const SET_PLAYER = 'SET_PLAYER';
const SET_BOMBS = 'SET_BOMBS';
const SET_STARS = 'SET_STARS';
const SET_SCORE_BOARD = 'SET_SCORE_BOARD';

export {
	SET_GAME,
	SET_PLAYER,
	SET_SCORE,
	SET_BOMBS,
	SET_STARS,
	SET_PLATFORMS,
	SET_SCORE_BOARD,
};
